### ISSUE TITLE
Variáveis de estado

### ISSUE THREAD

**Issue by andre06santos** [andre06santos/bloco-de-notas#51]
Sobre `state`:

- [x] Entender o conceito
- [x] Para que serve
- [x] Qual relação possui com a rerenderização da página
- [x] Qual relação com o conceito de reconciliação

**Comment by GiseleBCSantos** [comment]
Uma variavel de estado e uma variavel criada usando o hook useState que retorna uma variavel e uma função que altera essa variavel [count, setCount]. 

Ela serve pra guardar informacoes importantes naquele component ou em seus filhos, e a função para alterar serve para alterar seu valor. E importante que ao se alterar um estado nao o altere diretamente (setCount(count + 1)), e sim o faca indiretamente (setCount(prevCount => prevCount + 1))). (**Isso eu sei pois aprendi em cursos, mas nao sei bem o porque**)

Cada vez que o valor da variavel e alterado pela sua função propria (setCount), o component e renderizado novamente, podendo Fazer com que surjam diversos problemas de renderizacoes extras.

A reconciliacao e um mecanismo em que, durante a mudanca de estado em uma parte da pagina, ele verifica em quais components sera necessario ser feito o mount novamente devido aquela alteracao. Ja nos components onde essa mudanca de estado nao tem influencia, nao ha a necessidade de ser feito o mount novamente.
