### ISSUE TITLE
Hooks do React

### ISSUE THREAD

**Issue by andre06santos** [andre06santos/bloco-de-notas#59]
Entender o que são e como funcionam os hooks abaixo:

- [x] useEffect()
- [x]  useCallback()
- [x]  useMemo()

**Comment by Thalis78** [comment]
## Hooks:
Hooks são funções no react que permitem utilizar o estado e outros recursos do React em componentes funcionais, sem precisar escrever componentes de classes.

useEffect: relacionado a efeitos colaterais (ações que ocorrem fora do fluxo principal de execução do código), é utilizado para gerenciar esses efeitos, evitando que interfiram no layout ou causem atrasos na renderização.
useCallbacl: Memoriza uma função, para que ela não seja recriada em cada renderização.
useMemo: Memoriza valores calculados para evitar cálculos repetidos.
